FROM mcr.microsoft.com/mssql/server:2019-latest AS build
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=SuperPassword123

WORKDIR /tmp
COPY Manufacturing_db_backup.bak .
COPY restore.sql .

RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 5 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "SuperPassword123" -i /tmp/restore.sql \
    && pkill sqlservr

FROM mcr.microsoft.com/mssql/server:2019-latest AS release
ENV ACCEPT_EULA=Y
COPY --from=build /var/opt/mssql/data /var/opt/mssql/data
