//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoView
    {
        public string UserLogin { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string ResidentialAddress { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Passport { get; set; }
        public Nullable<int> ContactId { get; set; }
        public byte[] Photo { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    }
}
